---
title: "Title of the Article"
author:
  - name: "First Author's name"
    authsuperscript: 1*
  - name: "Second Author's name"
    authsuperscript: 2
affiliation:
  - affsuperscript: 1
    dptuniv: "Department / University"
    address: >
      Street address,
      Zip code,
      Country.
  - affsuperscript: 2
    dptuniv: "Department / University"
    address: >
      Street address,
      Zip code,
      Country.
# Corresponding Author
corrauthor:
    email: name@company.com
    url: https://www.company.com
abstract: >
  Summary of the article.
keywords: [keyword1, keyword2, etc]
# First Page Header
journalinfo: "Publication reference"
archive: "DOI: xxx/xx"
# Date format: '%Y %B %d' for distill
date: "`r format(Sys.time(), '%Y %B %d')`"
url: https://GitHubID.github.io/Repository/
github-repo: GitHubID/Repository
# Language
lang: en-US
otherlangs: [fr-FR,it]
keywordlabel: Keywords
corrauthorlabel: Corresponding author
# Bibliography
bibliography: references.bib
biblio-style: chicago
# LaTeX
toc-depth: 3
fontsize: 10pt
urlcolor: blue
preamble: >
  \hyphenation{bio-di-ver-si-ty sap-lings}
# Do not modify
always_allow_html: yes
csquotes: true
output:
  bookdown::html_document2:
    base_format: distill::distill_article
    toc: yes
    toc_float: yes
    code_folding: show
    highlight_downlit: yes
  rmdformats::downcute:
    use_bookdown: yes
    lightbox: yes
  bookdown::gitbook:
    config:
      download: "pdf"
      sharing:
        github: yes
  bookdown::pdf_book:
    template: latex/template.tex
    citation_package: natbib
    latex_engine: xelatex
    keep_tex: yes
  bookdown::word_document2: default
---

```{r}
#| label: DoNotModify
#| include: false
### Utilities. Do not modify.
# Installation of packages if necessary
InstallPackages <- function(Packages) {
  InstallPackage <- function(Package) {
    if (!Package %in% installed.packages()[, 1]) {
      install.packages(Package, repos = "https://cran.rstudio.com/")
    }
  }
  invisible(sapply(Packages, InstallPackage))
}

# Basic packages
InstallPackages(c("bookdown", "formatR", "kableExtra", "ragg"))

# kableExtra must be loaded 
if (knitr::opts_knit$get("rmarkdown.pandoc.to") == "docx") {
  # Word output (https://stackoverflow.com/questions/35144130/in-knitr-how-can-i-test-for-if-the-output-will-be-pdf-or-word)
  # Do not use autoformat (https://github.com/haozhu233/kableExtra/issues/308)
  options(kableExtra.auto_format = FALSE)
}
library("kableExtra")

# Chunk font size hook: allows size='small' or any valid Latex font size in chunk options
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

```{r}
#| label: Options
#| include: false
### Customized options for this document
# Add necessary packages here
Packages <- c("tidyverse")
# Install them
InstallPackages(Packages)

# knitr options
knitr::opts_chunk$set(
  cache =   FALSE,    # Cache chunk results
  include = TRUE,     # Show/Hide chunks
  echo =    TRUE,     # Show/Hide code
  warning = FALSE,    # Show/Hide warnings
  message = FALSE,    # Show/Hide messages
  # Figure alignment and size
  fig.align = 'center', out.width = '80%',
  # Graphic devices (ragg_png is better than standard png)
  dev = c("ragg_png", "pdf"),
  # Code chunk format
  tidy = TRUE, tidy.opts = list(blank = FALSE, width.cutoff = 50),
  size = "scriptsize", knitr.graphics.auto_pdf = TRUE
  )
options(width = 50)

# ggplot style
library("tidyverse")
theme_set(theme_bw())
theme_update(
  panel.background = element_rect(fill = "transparent", colour = NA),
  plot.background = element_rect(fill = "transparent", colour = NA)
)
knitr::opts_chunk$set(dev.args = list(bg = "transparent"))

# Random seed
set.seed(973)
```
